name: 'dbtclass'
version: '1.0.0'
config-version: 2

models:
  dbtclass:
    staging:
      +materialized: view
    marts:
      core:
        +materialized: table

# Optional sections (top-level, not nested under dbtclass)
