name: 'dbtclass'
version: '1.0.0'
config-version: 2

# Define model materializations by folder
models:
  dbtclass:
    staging:
      +materialized: view
    marts:
      core:
        +materialized: table

# Optional: specify seeds, snapshots, and tests if you use them
seeds:
  +schema: seeds

snapshots:
  +target_schema: snapshots

tests:
  +severity: warn
